#Choose the percentage threshold of ready teams at which the game should start
minimal-ready-teams-percentage-to-start: 60

#Choose the threshold of ready teams at which the game should start (in combination with the percentage condition)
minimal-ready-teams-to-start: 2

#Choose the minimum number of players connected  to start the countdown when team are ready (in combination with the two above options)
min-players-to-start: 0

#Choose how much players can be in the same team, set it to 1 to play a game with no teams
max-players-per-team: 2

#If true every team will get a random team color.
use-team-colors: true

#Choose if new players will be auto assigned to a not full team.
auto-assign-new-player-team: false

#If true, all players with no team when the game starts, will be assigned to a team that is not full.
#If no team can be found, the player will remain solo
#Be warned that it will even force two solo players to be in the same team, resulting in a game with only one team, thus ending instantly.
#To avoid this wierd case you must set your min-players-to-start value to be higher than the max-players-per-team value
force-assign-solo-player-to-team-when-starting: false

#Set it to true to prevent players from leaving their team (may be useful with auto-assign set to true)
prevent-player-from-leaving-team: false

#Forces the teams to be always ready, thus preventing afk players from blocking the beginning of the game
team-always-ready: false

#Choose the coundown time to start the game when enough teams are ready
#This value must be set to 6 or more. If you set a value of 5 or less, it will cause an unpredictable behavior.
time-to-start-when-ready: 15

#The time is seconds before the PVP starts
time-before-pvp: 600

#Set it to false to kick player when they die. (Give players the permission 'uhc-core.spectate.override' to always allow them to spectate)
can-spectate-after-death: false

#Set it to true to allow new players to join as spectators when the game is already running (it requires can-spectate-after-death to be true)
# (Give players the permission 'uhc-core.spectate.override' to always allow them to spectate)
can-join-as-spectator: false

#Set it to false to block spectators from sending messages (Players with the permission 'uhc-core.chat.override' will still be able to talk)
can-send-messages-after-death: false

# Chat prefix, when enabled, messages starting with @ will display in team chat, when starting with ! they will be displayed in global chat.
# This means players don't have to use /chat to toggle between team and global chat each time.
chat-prefix:
  enable: false
  team-prefix: '@'
  global-prefix: '!'


#Configure after how many seconds a disconnected player should be considered dead and eliminated
kill-disconnected-players-after-delay:
  enable: true
  delay: 20

#Timer in seconds to auto stop/restart the server when the game as ended (Set to -1 to disable)
time-before-restart-after-end: 30

#Set it to false to prevent the end of the game if there are no players left (may be useful for private servers with friends playing over several days,
# it still requires the server to be left running while there are no players on it)
countdown-ending-game-when-all-players-have-left: true

# Enable to have a message and sound every x minutes. (This can be used for youtubers to know when to end their episodes.)
episode-markers:
  enable: false
  # Duration of the episodes in seconds.
  delay: 900

#Choose the potions effects to be given to the players when the game starts
#syntax = POTION_NAME/duration_in_ticks/amplifier
#reference list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
potion-effect-on-start:
  - DAMAGE_RESISTANCE/900/100
  - REGENERATION/900/10

# Customize game behavior to add non-standard minecraft things
customize-game-behavior:

  # Set a list of scenarios that are active by default. Set to true when you want to use this feature.
  enable-default-scenarios: true

  # You can change these for individual game using /scenarios (permission: 'uhc-core.scenarios.edit')
  # You can choose from these scenarios: CUTCLEAN, FIRELESS, BOWLESS, RODLESS, BLOODDIAMONDS, TIMBER, HORSELESS,
  # TIMEBOMB, NOFALL, BESTPVE, TRIPLEORES, TEAMINVENTORY, NOCLEAN, HASTEYBOYS, LUCKYLEAVES, BLEEDINGSWEETS,
  # DOUBLEGOLD, GOLDLESS, SWITCHEROO, VEINMINER
  active-scenarios:
    - TIMEBOMB
    - HASTEYBOYS

  scenarios:
    # When enabled players will be able to vote for what scenarios they want to be active.
    voting:
      enable: false
      # The amount of scenarios players can vote for.
      max-votes: 3
      # The amount of scenarios with the most votes that will get added at the start of the game.
      elected-scenarios: 3

  # Set it to true to allow ghast from dropping tears
  # Setting it to false is a good way to prevent people from making regeneration potions
  allow-ghast-tears-drops: true


  # Enable extra experience drops when killing a player (experience quantities reference http://minecraft.gamepedia.com/Experience)
  add-xp-drops-on-player-death:
    enable: true
    quantity: 200

  # Enable random extra gold drops for specific mobs
  # Entity types reference list here : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
  add-gold-drops:
    enable: true
    min: 1
    max: 3
    drop-chance-percentage: 50
    affected-mobs:
      - CREEPER
      - GHAST

  # Enable extra max life for every player
  add-player-extra-half-hearts:
    enable: true
    extra-half-hearts: 20

  # Add custom crafts

  # Set it to true to enable the need of a permission to use a custom craft
  # Permissions node will be like uhc-core.craft.light-apple
  enable-crafts-permissions: false

  add-custom-crafts:
    # Name of your craft, then 1, 2, 3 for every line in the crafting table
    # Please respect this syntax: ITEM/quantity/damage_value
    # To view the correct item item data you can use '/iteminfo' in game (Permission: 'uhc-core.commands.iteminfo')
    # Set limit to -1 to allow unlimited crafts, set to to a value greater than 0 to limit crafts by player
    # You can add enchantments in the enchants list (see the war-axe example)
    # Allowed enchantments names : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
    # Set default name to true to keep the default minecraft name. This means the custom crafted items will stack with other items created using default minecraft crafts.
    # (NOTE: When default name is enabled you will not be able to use craft limit and craft permissions!)
    'Light Apple':
      '1': AIR/1/0 GOLD_INGOT/1/0 AIR/1/0
      '2': GOLD_INGOT/1/0 APPLE/1/0 GOLD_INGOT/1/0
      '3': AIR/1/0 GOLD_INGOT/1/0 AIR/1/0
      craft: GOLDEN_APPLE/1/0
      default-name: true
      enchants: []
      limit: -1
    'Light Anvil':
      '1': IRON_INGOT/1/0 IRON_INGOT/1/0 IRON_INGOT/1/0
      '2': AIR/1/0 IRON_BLOCK/1/0 AIR/1/0
      '3': IRON_INGOT/1/0 IRON_INGOT/1/0 IRON_INGOT/1/0
      craft: ANVIL/1/0
      default-name: false
      enchants: []
      limit: 2
    'War Axe':
      '1': IRON_INGOT/1/0 IRON_INGOT/1/0 AIR/1/0
      '2': IRON_INGOT/1/0 IRON_BLOCK/1/0 AIR/1/0
      '3': AIR/1/0 IRON_BLOCK/1/0 AIR/1/0
      craft: IRON_AXE/1/0
      default-name: false
      enchants:
        - DAMAGE_ALL 2
        - FIRE_ASPECT 1
      limit: 1

  #Max building height (Set to -1 to disable).
  max-building-height: -1

  #Set it to true to prevent players from entering the nether through a portal
  ban-nether: false

  # Set it to true to enable the end.
  # Only set this to true when you are really using it since more worlds loaded means worse performance.
  enable-the-end: false

  #A list of items that you don't want players to be able to craft
  # To view the correct item item data you can use '/iteminfo' in game (Permission: 'uhc-core.commands.iteminfo')
  # Syntax ITEM_NAME/DAMAGE_VALUE
  # To remove all items change to "ban-items-crafts: []"
  ban-items-crafts:
    - GOLDEN_APPLE/1

  #Set it to true to prevent players from making level II potions with glowstone
  ban-level-2-potions: false

  #Set it to false to get the normal day light cycle
  always-day: true


  # Set it to true to allow droping a player head when a player dies
  # Eating the head regenerates your team for 5 seconds
  add-regen-head-drop-on-player-death: false


  # When golden heads are enabled on players death a skull will drop.
  # This skull can be placed in a crafting table with 8 gold around it to craft a "Golden Apple".
  # Golden heads heal 4 hearths instead of 2 for normal golden apples.
  enable-golden-heads: true


  # Set it to false to disable the sound on player death
  # Sound names reference list : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sound-on-player-death: WITHER_SPAWN

# This section references optional features to allow to run in fast uhc mode ( = uhc run)
fast-mode:

  underground-nether:
    # Set it to true to allow pasting a nether schematic file in the overworld.
    # The file should be named nether.schematic and be located in the plugins/UhcCore folder
    # If enabled, it will be pasted at random places in the world
    enable: false

    # Choose the min number of times the schematic will be pasted at random places
    min-ocurrences: 5

    # Choose the max number of times the schematic will be pasted at random places
    max-ocurrences: 10

    # Choose the height at which the schematic should be pasted
    paste-nether-at-y: 20

  # Configure customizable block loots
  # The name of the sub-category should be an existing block material
  # To view the correct item item data you can use '/iteminfo' in game (Permission: 'uhc-core.commands.iteminfo')
  # You can set 'loot' and 'add-xp' to drop an item or some xp
  # The item syntax is MATERIAL/AMOUNT/DAMAGE
  # If you do not want to have special loots, just leave the config node empty like that block-loot: {}
  block-loot:
    # Set to true to enable this feature
    enable: false

    loots:
      # It will drop 4 torches when breaking a coal ore block
      COAL_ORE:
        loot: TORCH/4/0

      # It will drop 2 iron ingots when breaking a iron ore block
      # It will also drop 3 xp
      IRON_ORE:
        loot: IRON_INGOT/2/0
        add-xp: 3

      # It will drop 2 gold ingots when breaking a gold ore block
      # It will also drop 3 xp
      GOLD_ORE:
        loot: GOLD_INGOT/2/0
        add-xp: 3

      # It will drop 2 diamonds when breaking a diamond ore block
      # It will also drop 5 xp
      DIAMOND_ORE:
        loot: DIAMOND/2/0
        add-xp: 5

      # It will drop 4 arrows when breaking a gravel block
      GRAVEL:
        loot: ARROW/4/0

  # Configure customizable mob loots
  # The name of the sub-category should be an existing entity type
  # See reference list here : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  # You can set 'loot' and 'add-xp' to drop an item or some xp
  # The item syntax is MATERIAL/AMOUNT/DAMAGE
  # If you do not want to have special loots, just leave the config node empty like that mob-loot: {}
  mob-loot:
    # Set to true to enable this feature
    enable: false

    loots:
      #It will drop 1 string and 2 xp when killing sheep.
      SHEEP:
        loot: STRING/1/0
        add-xp: 2


  # Generate extra sugar cane
  generate-sugar-cane:
    # Set to true to enable this feature.
    enable: true
    # The percentage of spannable blocks populated with sugar cane. (100 means 100% of the grass/sand blocks along water are filled with sugar cane.)
    percentage: 10

  # Having this enabled means ocean biomes will be replaced with planes and forrest.  (ONLY FOR 1.8!)
  replace-ocean-biomes: false

  # Generates more ore in the map
  generate-vein:

    # Set it to true to enable this feature.
    # If requires pre-generate-world to be enabled in order to generate more ores
    enable: false

    # Configure the blocks to be generated
    # The names should be existing material names
    # To view the correct item item data you can use '/iteminfo' in game (Permission: 'uhc-core.commands.iteminfo')
    veins:

      COAL_ORE:
        # Minimum generated veins per chunk
        min-veins-per-chunk: 2

        # Maximum generated veins per chunk
        max-veins-per-chunk: 5

        # Minimum generated block per vein
        min-blocks-per-vein: 5

        # Maximum generated block per vein
        max-blocks-per-vein: 10

        # Minimum y height where the vein will be generated
        min-y: 0

        # Maximum y height where the vein will be generated
        max-y: 60

      # Same config with other ores ...
      IRON_ORE:
        min-veins-per-chunk: 2
        max-veins-per-chunk: 10
        min-blocks-per-vein: 4
        max-blocks-per-vein: 8
        min-y: 0
        max-y: 60
      GOLD_ORE:
        min-veins-per-chunk: 2
        max-veins-per-chunk: 5
        min-blocks-per-vein: 2
        max-blocks-per-vein: 8
        min-y: 0
        max-y: 60
      DIAMOND_ORE:
        min-veins-per-chunk: 2
        max-veins-per-chunk: 4
        min-blocks-per-vein: 2
        max-blocks-per-vein: 5
        min-y: 0
        max-y: 60
      LAPIS_ORE:
        min-veins-per-chunk: 2
        max-veins-per-chunk: 4
        min-blocks-per-vein: 2
        max-blocks-per-vein: 4
        min-y: 0
        max-y: 60
      REDSTONE_ORE:
        min-veins-per-chunk: 2
        max-veins-per-chunk: 5
        min-blocks-per-vein: 4
        max-blocks-per-vein: 6
        min-y: 0
        max-y: 60
      EMERALD_ORE:
        min-veins-per-chunk: 2
        max-veins-per-chunk: 2
        min-blocks-per-vein: 1
        max-blocks-per-vein: 3
        min-y: 0
        max-y: 60


#Set it to true to enable kit permissions support.
#You then have to give players permissions like uhc-core.kit.tools
enable-kits-permissions: false

#Edit kits here, to remove all kits write only an empty node: "kits: {}"
kits:
  #Choose a keyword for the kit (not displayed in game)
  tools:
    symbol:
      #Choose what item will represent the kit
      item: STONE_PICKAXE
      #Choose the name of the item
      name: Kit Tools
    #Write a list of item following the syntax "number item"
    # To view the correct item item data you can use '/iteminfo' in game (Permission: 'uhc-core.commands.iteminfo')
    items:
      - 1 STONE_SWORD
      - 1 STONE_PICKAXE
      - 1 STONE_AXE

  #Write other kits
  ench:
    symbol:
      item: ENCHANTED_BOOK
      name: Enchanting
    items:
      - 15 PAPER
      - 5 LEATHER

#Options to configure the playing compass
playing-compass:
  #If set to false the playing compass will be removed from the game.
  enable: true
  #Compass mode:
  # 1 = The compass will point towards teammates when right-clicking it
  # 2 = The compass will point towards enemy's when right-clicking it
  # 3 = The compass will point towards all players when right-clicking it
  mode: 1

# Set to true if you want to enable hearts on tab.
hearts-on-tab: true

#Set it to true to give the spectating players access to the '/teleport <player>' command to teleport to playing players
spectating-teleport: true

#Options to pre-generate the world
pre-generate-world:
  #If set to true, the plugin will generate every chunks inside the world border
  enable: false

  #Delay in ticks to suspend the generation to avoid server crashing
  rest-every-ticks: 20

  #Duration of the rest in ticks
  rest-duration: 20

  #Maximum number of chunks loaded each tick
  chunks-per-tick: 10

#Setting up the world border
border:
  #Set it to true to make the border reduce slowly
  moving: false

  #Starting size of the border (500 means +500x, -500x, +500z, -500z)
  start-size: 500

  #End size of the border (200means +200x, -200x, +200z, -200z)
  end-size: 200

  #If moving is set to true, the time in seconds for the border to shrink to end-size
  time-to-shrink: 3600

  #If moving is set to true, the time in seconds for the border before it starts moving
  time-before-shrink: 0


#Setting up the time limit
time-limit:
  #Set it to false to make an endless game until one team wins
  enable: true

  #The time in seconds for the time limit
  limit: 3600

  #Set it to true if you want a deathmatch after the time-limit (time-limit must be true)
  #For this to work, you must have WorldEdit installed and your arena.schematic file inside plugins/UhcCore
  end-with-deathmatch-after-time-limit: false

  #Set it to true if you want players in deathmatch to be in adventure mode. (false = survival mode)
  deathmatch-adventure-mode: true

  # Choose a rare block type that will create team teleport spots in the deathmatch arena
  # To view the correct item item data you can use '/iteminfo' in game (Permission: 'uhc-core.commands.iteminfo')
  deathmatch-teleport-spots-block: BEDROCK

  # The arena.schematic is pasted at x=10000 z=10000, you can choose here the y coordinate
  paste-arena-at-y: 100

worlds:
  # Having this set to true means the name of your uhc world don't change. This is not suggested since it may couse some worlds to not load correctly.
  permanent-world-names: false

#Write custom seeds to be used when creating a new map
world-seeds:
  #Set it to true to pick a random seed from this list
  pick-random-seed-from-list: false

  #Write here custom seeds
  list:
    - 8708477303049171819
    - 4718448332187272495

#Write existing world name in your server folder to copy and play on a map you have created
world-list:
  #Set it to true to use that feature (you must set pick random seed to false also)
  pick-random-world-from-list: false
  #A list of your existing world folders
  list:
    - your_world
    - your_second_world

#Enable bungee-coord support to send players back to the server of your choice when the game ends
bungee-support:
  #Set it to true to send players back to a server at the end
  enable: false
  #Set it to true if you want players to get a return to lobby item on their hotbar.
  use-lobby-item: true
  #The name of the server (same as in your bungee config)
  send-players-to-server-after-end: lobby
  #Time (in seconds) before sending the player to the hub (If spectating after death is disabled and they don't have the permission 'uhc-core.spectate.override').
  time-before-send-after-death: 0
  #Time (in seconds) before sending all the players to the hub after the game has ended
  time-before-send-after-end: 0

#Reward your players for taking achievements (kills, win, playing time).
#Require Vault and an Economy plugin compatible with Vault (I recommend CraftConomy)
custom-events:
  #Reward a player a price in your economy currency every time he is still alive after the interval (in seconds)
  time:
    enable: false
    reward: 100
    interval: 600
  #Reward a player a price in your economy currency every time he kills an enemy
  kill:
    enable: false
    reward: 500
  #Reward a price in your economy currency to the winners of the game
  win:
    enable: false
    reward: 1000

# When set to true, the plugin won't delete the last world, it will just load it. It will also ignore the map pre-generator.
# This is to allow fast-configuration, to avoid creating new worlds when you only want to configure some other features.
debug: false
# When set to true, the game won't end when only one player is left. This can be used to play alone in order to test games.
one-player-mode: false